// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    copy: typeof import('./src/components/PropertySwitchDragableTableComponent copy.vue')['default']
    CreateNewComponent: typeof import('./src/components/CreateNewComponent.vue')['default']
    DragableTableComponent: typeof import('./src/components/DragableTableComponent.vue')['default']
    EmptyComponent: typeof import('./src/components/EmptyComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    IconMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IconMdiEye: typeof import('~icons/mdi/eye')['default']
    LeadByStatusComponent: typeof import('./src/components/LeadByStatusComponent.vue')['default']
    LeadFormComponent: typeof import('./src/components/LeadFormComponent.vue')['default']
    LoginFormComponent: typeof import('./src/components/LoginFormComponent.vue')['default']
    LoginModalComponent: typeof import('./src/components/LoginModalComponent.vue')['default']
    ModalComponent: typeof import('./src/components/ModalComponent.vue')['default']
    NewElementButtonComponent: typeof import('./src/components/NewElementButtonComponent.vue')['default']
    PropertySwitchDragableTableComponent: typeof import('./src/components/PropertySwitchDragableTableComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
