// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    copy: typeof import('./src/components/LoginModalComponent copy.vue')['default']
    EmptyComponent: typeof import('./src/components/EmptyComponent.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    LoginFormComponent: typeof import('./src/components/LoginFormComponent.vue')['default']
    LoginModalComponent: typeof import('./src/components/LoginModalComponent.vue')['default']
    ModalComponent: typeof import('./src/components/ModalComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
